# This workflow will build and push a Python application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-python?tabs=bash&pivots=python-framework-flask
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the PYTHON_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest
          
      - name: Create artifact directory
        run: mkdir -p artifacts/python-app

      - name: Copy necessary files to artifact directory
        run: |
          cp -r backend artifacts/python-app/backend
          if [ -d "other_directory" ]; then
            cp -r other_directory artifacts/python-app/other_directory
          fi
      
      - name: Archive artifact
        run: |
          cd artifacts
          tar -czf python-app.tar.gz python-app
          cd ..
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: python-app
          path: artifacts/python-app.tar.gz
          if-no-files-found: error
          compression-level: 6
          overwrite: false

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: QuickSearch_Estates
          slot-name: production
          package: artifacts/python-app.tar.gz
          subscription-id: f82595b3-47a0-49a2-8e87-b1e0f2e2f999
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.8.18/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib
