name: Deploy QuickSearch_Estates to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build and deploy
        run: |
          npm install  # Or any build commands you need
          npm run build  # Or any build commands you need
          npx gh-pages -d dist  # Or the directory where your static files are generated
        env:
          NODE_ENV: production
        working-directory: ./QuickSearch_Estates

  register_app:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Register GitHub App
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: app } = await github.apps.create({
              name: 'QuickSearch_Estates',
              description: 'GitHub App for deploying static content to GitHub Pages',
              homepage_url: 'https://github.com/CarltonNcube/QuickSearch_Estates',
              redirect_uris: ['https://github.com/CarltonNcube/QuickSearch_Estates/callback'],
              external_url: 'https://github.com/CarltonNcube/QuickSearch_Estates',
              default_permissions: {
                contents: 'read',
                pages: 'write',
                id_token: 'write'
              },
              installation_target_type: 'all',
              events: ['repository']
            });
            console.log(`GitHub App registered. App ID: ${app.id}`);
