name: Deploy QuickSearch_Estates to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build and deploy
        run: |
          cd QuickSearch_Estates  # Change directory to QuickSearch_Estates
          npm install  # Or any build commands you need
          npm run build  # Or any build commands you need
          npx gh-pages -d dist  # Or the directory where your static files are generated
        env:
          NODE_ENV: production
