name: Deploy QuickSearch_Estates to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Configure Git identity
        run: |
          git config --global user.email "carltonncube@outlook.com"
          git config --global user.name "CarltonNcube"

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build and deploy
        run: |
          cd frontend
          npm install
          npm run build
          git push git@github.com:CarltonNcube/QuickSearch_Estates.git master
